name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
    steps:
      - uses: actions/checkout@v4
      - uses: Platane/snk@v3
        with:
          github_user_name: shir1nka
          outputs: |
            output/github-contribution-grid-snake.svg?palette=github-dark
            output/github-contribution-grid-snake-dark.svg?palette=github-dark
      - run: |
          git config user.name "shir1nka"
          git config user.email "dierahodzaeva28@gmail.com"
          git add output/
          git commit -m "update contribution snake" || true
      - env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --unset-all http.https://github.com/.extraheader || true
          git remote set-url origin https://shir1nka:${GH_PAT}@github.com/shir1nka/shir1nka.git
          git push origin master
