name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Platane/snk@v3
        with:
          github_user_name: shir1nka
          outputs: |
            output/github-contribution-grid-snake.svg?palette=github-dark
            output/github-contribution-grid-snake-dark.svg?palette=github-dark
      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "update contribution snake"
          add: "output/"
          github_token: ${{ secrets.GH_PAT }}
